esphome:
  name: aquariumlid

esp32:
  board: esp32-c3-devkitc-02
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "NotSoSmart"
  password: "IOTGeraeteSindSchrott"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aquariumlid Fallback Hotspot"
    password: "L1ckdqb8JCSk"

captive_portal:



    