[package]
edition      = "2024"
name         = "firmware"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "firmware"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "~1.1", features = ["defmt", "esp32c3", "unstable"] }

esp-rtos = { version = "0.3", features = [
  "defmt",
  "embassy",
  "esp-alloc",
  "esp-radio",
  "esp32c3",
] }

defmt                  = "1.0.1"
esp-bootloader-esp-idf = { version = "0.5", features = ["defmt", "esp32c3"] }

embassy-net = { version = "0.9.1", features = [
  "defmt",
  "dhcpv4",
  "dhcpv4-hostname",
  "medium-ethernet",
  "tcp",
  "udp",
  "dns",
  "proto-ipv4",
  "proto-ipv6",
] }
embedded-io = { version = "0.7.1", features = ["defmt"] }
embedded-io-async = { version = "0.7.0", features = ["defmt"] }
esp-alloc = { version = "0.10", features = ["defmt"] }
esp-backtrace = { version = "0.19", features = [
  "defmt",
  "esp32c3",
  "panic-handler",
] }
esp-println = { version = "0.17", features = ["defmt-espflash", "esp32c3"] }
bt-hci = "0.8"
embassy-executor = { version = "0.10", features = ["defmt"] }
embassy-time = { version = "0.5", features = ["defmt"] }
esp-radio = { version = "0.18.0", features = [
  "ble",
  "coex",
  "defmt",
  "esp-alloc",
  "esp32c3",
  "unstable",
  "wifi",
] }
smoltcp = { version = "0.13", default-features = false, features = [
  "defmt",
  "medium-ethernet",
  "multicast",
  "proto-dhcpv4",
  "proto-dns",
  "proto-ipv4",
  "socket-dns",
  "socket-icmp",
  "socket-raw",
  "socket-tcp",
  "socket-udp",
  "proto-ipv6",
] }
# trouble-host = { version = "0.6", features = ["gatt", "derive", "defmt"] }
trouble-host = { git = "https://github.com/embassy-rs/trouble.git", rev = "4bf65472d2606d3af43f9c4e18bc7ef9a46c5b14", features = ["gatt", "derive", "defmt"] }

critical-section = "1.2.0"
static_cell      = "2.1"
aht20 = { git = "https://github.com/mawoka-myblock/ambient-air.git" }
smart-leds = "0.4"
esp-hal-smartled = { git = "https://github.com/mawoka-myblock/esp-hal-smartled.git", branch = "update-esp-hal", features = ["defmt"] }
esp-ds18b20 = { git = "https://github.com/abreis/esp-ds18b20" }
esp-onewire = { git = "https://github.com/abreis/esp-onewire", tag = "v1.0.0" }
embedded-storage = { version = "*" }
embassy-sync = { version = "0.8" }
portable-atomic = { version = "1.13", default-features = false }
tickv = { version = "2" }
anyhow = { version = "*", default-features = false }
esp-storage = { version  = "0.9", features = ["esp32c3"] }
embassy-futures = { version = "*" }
sine_macro = { version = "0.1" }
heapless = { version = "*", features = ["serde"] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde-json-core = { version = "0.6" }
itoa = { version = "1" }
picoserve = { version = "0.18", features = ["embassy", "defmt", "json"] }
postcard = { version = "1", features = ["use-crc"] }
crc = { version = "*" }
rust-mqtt = { version = "0.5.1", default-features = false, features = ["defmt", "bump", "v5"]}
embedded-nal-async = {version = "0.9"}
async-button = { version = "0.2", features = ["defmt"] }

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units    = 1
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
